FROM tournament-base as build

# RUNTIME
FROM public.ecr.aws/lambda/nodejs:18

COPY package.json package-lock.json ${LAMBDA_TASK_ROOT}

COPY --from=build /usr/src/dist ${LAMBDA_TASK_ROOT}

COPY --from=build /usr/src/node_modules ${LAMBDA_TASK_ROOT}/node_modules

CMD ["index.handler"]
